[project]
name = "five-safes-tes-workbench"
# Makes the version dynamic
dynamic = ["version"]
description = "Common feature library for working with 5S-TES"
readme = "README.md"
authors = [
    { name = "CodeByKarthik", email = "karthikeyan.sivakumar2@nottingham.ac.uk" },
    { name = "Tri Thien Nguyen", email = "thien.nguyen1@nottingham.ac.uk" },
    { name = "Anwar Gaungoo", email = "anwar.gaungoo@nottingham.ac.uk" },
    { name = "Benjamin Partridge", email = "benjamin.partridge1@nottingham.ac.uk" },
]
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.43.99",
    "py-tes>=1.1.2",
    "pydantic>=2.13.1",
    "pyyaml>=6.0.3",
    "types-requests>=2.33.0.20260408",
]

[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

# Sources the version from version control
[tool.hatch.version]
source = "vcs"

[dependency-groups]
dev = [
    "mypy>=1.20.1",
    "mypy-boto3-s3>=1.43.93",
    "pytest>=8.0.0",
    "pytest-mock>=3.14.0",
    "ruff>=0.15.11",
    "types-pyyaml>=6.0.12.20260408",
]

docs = [
    "sphinx>=9.1.0",
    "furo>=2025.12.19",
]

[tool.pyright]
reportMissingTypeStubs = false

[tool.ruff]
line-length = 100
target-version = "py311"

[tool.ruff.lint]
select = [
    "E",     # pycodestyle errors
    "W",     # pycodestyle warnings
    "F",     # pyflakes
    "I",     # isort
]

[tool.ruff.lint.isort]
known-first-party = ["five_safes_tes_workbench"]

[tool.uv.workspace]
members = [
    "src/five_safes_tes_workbench/notebooks",
]
